OnlineVotingSystem/Controllers/AdminCandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineVotingSystem.Models;

namespace OnlineVotingSystem.Controllers
{
    public class AdminCandidateController : Controller
    {
        //
        // GET: /AdminCandidate/
        SystemDbNaya Db = new SystemDbNaya();
        public PartialViewResult Search(string q,string Filter)
        {                  var candidates = Db.Candidates.Where(r => r.Society.Contains(q));
            switch (Filter)
            {
                case "Candidate ID": candidates = Db.Candidates.Where(r => r.CandidateId.Contains(q)); break;
                case "Society": candidates = Db.Candidates.Where(r => r.Society.Contains(q)); break;

            }
   
            return PartialView("_CandidatesDisplay", candidates);

        }
        public ActionResult Index()
        {
            var candidates = Db.Candidates;
            return View(candidates);
        }

        //
        // GET: /AdminCandidate/Details/5

        public ActionResult Details(string CandidateId)
        {
            var candidate = Db.Candidates
                .Single(r => r.CandidateId == CandidateId);
            var voter = Db.Voters.Single(r => r.VoterId == CandidateId);
                  ViewBag.name=voter.Name;
            ViewBag.email=voter.EMail;

            return View(candidate);
        }

        //
        // GET: /AdminCandidate/Create

        public ActionResult Create()
        {
            return View(new Candidate());
        } 

        //
        // POST: /AdminCandidate/Create

        [HttpPost]
        public ActionResult Create(Candidate candidate)
        {
            try
            {
                var candidates = Db.Candidates;
                candidates.Add(candidate);
                Db.SaveChanges();
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /AdminCandidate/Edit/5
 
        public ActionResult Edit(string CandidateId )
        {
            var candidate = Db.Candidates.Single(r => r.CandidateId == CandidateId);

            return View(candidate);
        }

        //
        // POST: /AdminCandidate/Edit/5

        [HttpPost]
        public ActionResult Edit(string CandidateId, FormCollection collection)
        {
            try
            {
                var candidate = Db.Candidates.Single(r => r.CandidateId == CandidateId);
                TryUpdateModel(candidate);
                Db.SaveChanges();

                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /AdminCandidate/Delete/5
 
        public ActionResult Delete(string CandidateId)
        {
            var candidate = Db.Candidates.Single(r => r.CandidateId == CandidateId);

            return View(candidate );
        }

        //
        // POST: /AdminCandidate/Delete/5

        [HttpPost]
        public ActionResult Delete(string CandidateId, FormCollection collection)
        {
            try
            {
                var candidate = Db.Candidates;
                candidate.Remove(Db.Candidates.Single(r => r.CandidateId == CandidateId));
                Db.SaveChanges();
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineVotingSystem/Controllers/AdminVoterController.cs
using System.Linq;
using System.Web.Mvc;
using OnlineVotingSystem.Models;

namespace OnlineVotingSystem.Controllers
{
    public class AdminVoterController : Controller
    {
        //
        // GET: /AdminVoter/
        SystemDbNaya Db = new SystemDbNaya();
        public ActionResult Index()
        {
            var voters = Db.Voters;
            return View(voters);
        }

        //
        // GET: /AdminVoter/Details/5
           
        public ActionResult Details(string VoterId)
        {
            var re = Db.Voters
                .Single(r => r.VoterId == VoterId);

            return View(re);
        }

        //
        // GET: /AdminVoter/Create

        public ActionResult Create()
        {
            return View(new Voter());
        } 

        //
        // POST: /AdminVoter/Create

        [HttpPost]
        public ActionResult Create(Voter voter)
        {
            try
            {
                var rev = Db.Voters;
                rev.Add(voter);//Adding the voters, in the next step, we will be adding the user too

                var user = Db.Users;
                user.Add(new User
                {
                    UserId = voter.VoterId,
                    Password = voter.VoterId,
                    TypeOfUser = "Student"
                });

                Db.SaveChanges();

                // TODO: Add insert logic here
              
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /AdminVoter/Edit/5
 
        public ActionResult Edit(string VoterId)
        {
            var voter = Db.Voters.Single(r => r.VoterId == VoterId);

            return View(voter);
        }

        //
        // POST: /AdminVoter/Edit/5

        [HttpPost]
        public ActionResult Edit(string VoterId, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
               var voter = Db.Voters.Single(r => r.VoterId == VoterId);
               TryUpdateModel(voter);
               Db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /AdminVoter/Delete/5
 
        public ActionResult Delete(string VoterId)
        {
            var voter = Db.Voters
                .Single(r => r.VoterId == VoterId);

            return View(voter);
        }

        //
        // POST: /AdminVoter/Delete/5

        [HttpPost]
        public ActionResult Delete(string VoterId, FormCollection collection)
        {   //No two strings can have same number of arguements
            try
            {
                var voter = Db.Voters;
                voter.Remove(voter.Single(r => r.VoterId == VoterId));
                var user = Db.Users;
                user.Remove(user.Single(r => r.UserId == VoterId));
                Db.SaveChanges();
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Voting()
        {
            ViewBag.items = new[] { "Technical", "Cultural", "FilmAndMusic", "Sports" };
            return View(Db);
        }

         //For change password option
        public ActionResult ChangePassword()
        {
                         
            return View();
        }

        public PartialViewResult search(string q, string Filter)
        {
            var voters = Db.Voters.Where(r => r.Name.Contains(q));
            switch (Filter)
            {
                case "Name": voters = Db.Voters.Where(r => r.Name.Contains(q)); break;

                case "Department": voters = Db.Voters.Where(r => r.Department.Contains(q)); break;
                case "E-mail": voters = Db.Voters.Where(r => r.EMail.Contains(q)); break;
                

            }
           /// var voters = Db.Voters.Where(r => r.Name.Contains(q));
            return PartialView("_VotersDisplay", voters);


        }
        //public ActionResult QuickSearch(string term)
        //{
        //    var voter = Db.Voters
        //        .Where(r => r.Name.Contains(term))
        //        .Take(10)
        //        .Select(r => new { label = r.Name });
        //    return Json(voter, JsonRequestBehavior.AllowGet);

        //}

    }
}

OnlineVotingSystem/Controllers/CandidateMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineVotingSystem.Models;

namespace OnlineVotingSystem.Controllers
{
    public class CandidateMainController : Controller
    {
        static string ID;
        //
        // GET: /CandidateMain/
        SystemDbNaya Db = new SystemDbNaya();
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /CandidateMain/Details/5

        public ActionResult Profile(string id)
        {
            if (id == null)
                id = ID;
            ID = id;
            var candidate = Db.Candidates.Single(r => r.CandidateId == id);

            return View(candidate);
        }

        //
        // GET: /CandidateMain/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /CandidateMain/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /CandidateMain/Edit/5
 
        public ActionResult Edit(string id)
        {
            var candidate = Db.Candidates.Single(r => r.CandidateId == id);
            return View(candidate);
        }

        //
        // POST: /CandidateMain/Edit/5

        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            try
            {
                var candidate = Db.Candidates.Single(r => r.CandidateId == id);
                TryUpdateModel(candidate);
                // TODO: Add update logic here
                Db.SaveChanges();
                return RedirectToAction("Profile", new { ID = candidate.CandidateId });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /CandidateMain/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /CandidateMain/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //For changing password of the Candidate
        public ActionResult ChangePassword()
        {
            var user = Db.Users.Single(r => r.UserId == ID);
            return View(user);
        }
        [HttpPost]
        public ActionResult ChangePassword(string OldPassword, string ConfirmPassword, User user)
        {
            try
            {
                var us = Db.Users.Single(r => r.UserId == ID);
                if (OldPassword == us.Password)
                {
                    if (user.Password == ConfirmPassword)
                    {
                        TryUpdateModel(us);
                        Db.SaveChanges();
                        return View("ChangeSuccessful");
                    }
                    else
                    {
                        throw new Exception();
                    }
                }
                else
                    throw new Exception();

            }
            catch
            {
                // ViewBag.message="The Passwords don't match or your old password is wrong. Please try again";



                return View();
            }

        }
      
    }
}

OnlineVotingSystem/Controllers/VoterMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineVotingSystem.Models;

namespace OnlineVotingSystem.Controllers
{
    public class VoterMainController : Controller
    {
        //
        // GET: /VoterMain/
        SystemDbNaya Db = new SystemDbNaya();
        static string ID;
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /VoterMain/Details/5

        public ActionResult Profile(string id)
        {
            try
            {
                var voter = Db.Voters.Single(r => r.VoterId == id);
                ID = id;
                return View(voter);
            }
            catch
            {
                return RedirectToAction("Profile", new { id = ID });
            }
        }

 
        //
        // GET: /VoterMain/Edit/5
 
        public ActionResult Edit(string id)
        {
            var voter = Db.Voters.Single(r => r.VoterId == id);

            return View(voter);
        }

        //
        // POST: /VoterMain/Edit/5

        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                var voter = Db.Voters.Single(r => r.VoterId == id);
                TryUpdateModel(voter);
                Db.SaveChanges();
                return RedirectToAction("Profile", new { ID = voter.VoterId });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /VoterMain/Delete/5

        public ActionResult Vote()
        {
            try
            {
                var voter = Db.Voters.Single(r => r.VoterId == ID && r.Voted==0);
                var model = Db;
                ViewBag.items = new[] { "Technical", "Cultural", "FilmAndMusic", "Sports" };
                return View(model);
            }
            catch
            {

                return View("Voted");
            }
        }

        [HttpPost]
        public ActionResult Vote(string TechnicalId,string CulturalId,string FilmAndMusicId,string SportsId)
        {
            var vote = Db.Candidates
            .Single(r=>r.CandidateId==TechnicalId);
            vote.Votes = vote.Votes + 1;
            vote = Db.Candidates
.Single(r => r.CandidateId == CulturalId);
            vote.Votes = vote.Votes + 1;
            vote = Db.Candidates
            .Single(r => r.CandidateId == FilmAndMusicId);
            vote.Votes = vote.Votes + 1;
            vote = Db.Candidates
            .Single(r => r.CandidateId == SportsId);
            vote.Votes = vote.Votes + 1;
            Db.Voters.Single(r => r.VoterId == ID).Voted = 1;
            Db.SaveChanges();
            return View("Voted");
        }



        //For changing password of the voter
        public ActionResult ChangePassword()
        {
            var user = Db.Users.Single(r => r.UserId == ID);
            return View(user);
        }
        [HttpPost]
        public ActionResult ChangePassword(string OldPassword,string ConfirmPassword,User user)
        {
            try
            {
                var us = Db.Users.Single(r => r.UserId == ID);
                if (OldPassword == us.Password)
                {
                    if (user.Password == ConfirmPassword)
                    {
                        TryUpdateModel(us);
                        Db.SaveChanges();
                        return View("ChangeSuccessful");
                    }
                    else
                    {
                     throw new Exception();
                    }
                }
                else
                    throw new Exception();

            }
            catch
            {
                   // ViewBag.message="The Passwords don't match or your old password is wrong. Please try again";
                              


                return View();
            }
        
        }
    }
}

OnlineVotingSystem/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
  <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">

                <h1>Online Voting System</h1>
            </div>

             <div id="logindisplay">
     @*   @Html.Partial("_LogOnPartial")*@
      
            </div>
            <br />
            <br />
            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Voters", "Index", "AdminVoter")</li>
                    <li>@Html.ActionLink("Candidates", "Index", "AdminCandidate")</li>
                    <li>@Html.ActionLink("Voting","Voting","AdminVoter")</li>
                    <li>@Html.ActionLink("Logout","Index","Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

OnlineVotingSystem/Views/Shared/_CandidateLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Online Voting System</h1>
            </div>

             <div id="logindisplay">
     @*   @Html.Partial("_LogOnPartial")*@
      
            </div>
            <br />
            <br />
            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Profile", "Profile", "CandidateMain","ID")</li>
                     <li>@Html.ActionLink("Change Password","ChangePassword","Candidatemain")</li>
              
                    <li>@Html.ActionLink("Logout","Index","Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

OnlineVotingSystem/Views/Shared/_CandidatesDisplay.cshtml
@model IEnumerable<OnlineVotingSystem.Models.Candidate>


<table id="SearchResults">
    <tr>
    <th></th>        
    <th>
        Candidate ID
        </th>
        <th>
            Society
        </th>
        <th>
            Manifesto
        </th>
        <th>
            Votes
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { CandidateId=item.CandidateId }) |
            @Html.ActionLink("Details", "Details", new { CandidateId=item.CandidateId }) |
            @Html.ActionLink("Delete", "Delete", new { CandidateId=item.CandidateId })
        </td>
        <td>@item.CandidateId</td>
        <td>
            @item.Society
        </td>
        <td>
            @item.Manifesto
        </td>
        <td>
            @item.Votes
        </td>
    </tr>
}

</table>

OnlineVotingSystem/Views/Shared/_ChangePassword.cshtml
@model OnlineVotingSystem.Models.User

OnlineVotingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Online Voting System</h1>
           
            </div>

            <div id="logindisplay">
     @*   @Html.Partial("_LogOnPartial")*@
       <text>Welcome User</text>
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

OnlineVotingSystem/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

OnlineVotingSystem/Views/Shared/_VoterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="../../Scripts/BookDisplay.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery-ui.min.js" type="text/javascript"></script>
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Online Voting System</h1>
            </div>

             <div id="logindisplay">
     @*   @Html.Partial("_LogOnPartial")*@
      
            </div>
            <br />
            <br />
            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Profile", "Profile", "VoterMain")</li>
                    @*Actually Profile requires an ID, so make sure when you go to other click and come back, make sure everything works f9*@
                    <li>@Html.ActionLink("Vote","Vote","Votermain")</li>
                     <li>@Html.ActionLink("Change Password","ChangePassword","Votermain")</li>
                    <li>@Html.ActionLink("Logout","Index","Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

OnlineVotingSystem/Views/Shared/_VotersDisplay.cshtml
@model IEnumerable<OnlineVotingSystem.Models.Voter>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table id="SearchResults">
    <tr>
        <th></th>
        <th>
            VoterID
        </th>
        <th>
            Name
        </th>
        <th>
            Department
        </th>
        <th>
            EMail
        </th>
        <th>
            Voted
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { VoterId = item.VoterId }) |
            @Html.ActionLink("Details", "Details", new { VoterId = item.VoterId }) |
            @Html.ActionLink("Delete", "Delete", new { VoterId = item.VoterId })
        </td>
        <td>
            @item.VoterId
        </td>
        <td>
            @item.Name
        </td>
        <td>
            @item.Department
        </td>
        <td>
            @item.EMail
        </td>
        <td>
            @item.Voted
        </td>
    </tr>
}

</table>